### ISSUE TITLE
AdaptiveIndexDefrag-No msdb database in Azure SQL Server

### ISSUE THREAD

**Issue by stpete111** [microsoft/tigertoolbox#92]
I see the deployment script begins with USE msdb - Azure SQL Server has no msdb database like on-premise versions do (also, the USE command is not supported at all in Azure SQL Server).

I see in the Change Log that Azure SQL Server should now be supported.  

Can you please let me know how I should deploy this script on an Azure SQL Server with several databases?  Do I need to deploy it on each database individually?

Thanks.

**Comment by pmasl** [comment]
If you run this on Azure SQL Database **Managed Instance**, then choose which database to deploy to, and all databases should be handled from there (recommend to create a purposeful database for this).

Under Azure SQL Database, then deploy on each database.

**Comment by pmasl** [comment]
Hi, let me attempt to clarify. In order:

1) USE is supported in Azure SLQ DB Managed Instance, which I mentioned. See more about what T-SQL is not supported in Azure SQL DB Managed Instance in https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-transact-sql-information 

2) msdb exists in Azure SQL DB Managed Instance, or you may choose to create your own separate database. Same as in SQL Server.

3) If you use Azure SQL DB (single database service) rather than Azure SQL DB Managed Instance (database instance service), then there's only one database to deploy to: your own.

HTH

**Comment by stpete111** [comment]
Hi, I am still not able to deploy this script.

I do **not** use Azure SQL DB Managed Instance.  I use Azure SQL Server, with 5 databases.  I need to understand how I can run this script against each of my 5 databases being that, again, the USE statement is **not** supported in Azure SQL Server.

**Comment by mitchej7** [comment]
I'm suffering a similar problem. I had the same error message as above when installing - then when I run the script I get the following error.

**Command**
`EXEC dbo.usp_AdaptiveIndexDefrag @dbScope='myDb'`
**Error**
`Error 208 has occurred. Message: Invalid object name 'sys.dm_hadr_database_replica_states'. (Line Number: 1)`

I need to specify the `@dbScope` otherwise I get:
`Error 40515 has occurred. Message: Reference to database and/or server name in 'master.sys.databases' is not supported in this version of SQL Server. (Line Number: 16)`

I'm using Azure SQL Elastic Pools.

**Comment by mitchej7** [comment]
Is there any update on this? Still getting the same issue.

**Comment by sdahbour** [comment]
I'm having the same problem in Azure Sql Database (not managed instance).  I run the installation script (with @deploymode = 1 at the top).  I get the following output...

```
Droping existing objects
tbl_AdaptiveIndexDefrag_log table created
tbl_AdaptiveIndexDefrag_Analysis_log table created
tbl_AdaptiveIndexDefrag_Exceptions table created
tbl_AdaptiveIndexDefrag_Working table created
tbl_AdaptiveIndexDefrag_Stats_Working table created
tbl_AdaptiveIndexDefrag_Stats_log table created
tbl_AdaptiveIndexDefrag_IxDisableStatus table created
Procedure usp_AdaptiveIndexDefrag dropped
Procedure usp_AdaptiveIndexDefrag created
Reporting views created
Procedure usp_AdaptiveIndexDefrag_PurgeLogs created (Default purge is 90 days old)
Procedure usp_AdaptiveIndexDefrag_CurrentExecStats created (Use this to monitor defrag loop progress)
Msg 40515, Level 15, State 1, Procedure usp_AdaptiveIndexDefrag_Exceptions, Line 16 [Batch Start Line 3344]
Reference to database and/or server name in 'master.sys.sysdatabases' is not supported in this version of SQL Server.
Procedure usp_AdaptiveIndexDefrag_Exceptions created (If the defrag should not be daily, use this to set on which days to disallow it. It can be on entire DBs, tables and/or indexes)

All done!
```

The problem is happening when the script creates the usp_AdaptiveIndexDefrag_Exceptions stored procedure, in the line that says...
```
IF @exceptionMask_DB IS NULL OR QUOTENAME(@exceptionMask_DB) NOT IN (SELECT QUOTENAME(name) FROM master.sys.sysdatabases)
```

I commented the "OR" part of that and it works fine.  Of course, it won't check if the @exceptionMask_DB variable is a valid database name, which isn't optimal.  But I don't see a way to query the valid database names other than querying sys.sysdatabases, which you cannot do from a user database.

**Comment by jjabney** [comment]
Not sure why they proclaim it works in Azure SQL DB.  It's not compatible due to the sys.xxx references.

**Comment by pmasl** [comment]
This is fixed now.

**Comment by nitinkhosla79** [comment]
This is not fixed. I believe below needs to be added to one more line of code:
/* Recognize if database in scope is a Always On secondary replica */
		IF @dbScope IS NOT NULL AND @sqlmajorver >= 11 and (SELECT @@VERSION) NOT LIKE 'Microsoft SQL Azure%'

**Comment by nitinkhosla79** [comment]
one more error:
 Message: USE statement is not supported to switch between databases. Use a new connection to connect to a different database. (Line Number: 1)

**Comment by nitinkhosla79** [comment]
I have fixed the script to work with Azure Sql. Can someone review it?

[AZURE-SQL-INDEX-FRAGMENTATION-SCRIPT.TXT](https://github.com/microsoft/tigertoolbox/files/3374648/AZURE-SQL-INDEX-FRAGMENTATION-SCRIPT.TXT)

**Comment by beckerben** [comment]
@nitinkhosla79 your version seems to work from my testing on azure

**Comment by pmasl** [comment]
This would break the script for SQL Server and Azure SQL DB Managed Instance. Hence I changed it to use SERVERPROPERTY engineedition instead. Thanks for the help all, I'm uploading the revised version now!

**Comment by Almeonamy** [comment]
@pmasl, thanks!
Can you update script 3_job_AdaptiveIndexDefrag.sql for Azure Sql support?
